config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }

  root 'homes#index', as: 'home'

  resources :pizzas, only: %i[show index] do
    resources :reviews, only: :create
  end

  resource :cart, only: %i[show update]
  resource :order_items
  resource :fillings
  resource :custom_pizza

  resource :address, only: %i[edit update]
  resource :user_photo, except: :show
  resource :fast_authentificate, only: %i[create show]

  namespace :checkouts do
    resource :delivery, only: %i[show update]
    resource :address, only: %i[show update]
    resource :payment, only: %i[show create update]
    resource :confirm, only: %i[show create]
    resource :complete, only: %i[show]
  end

  resources :orders, only: %i[show index]
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/billing.rb
class Billing < Address
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :order
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pizzas, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
end

app/models/custom_pizza.rb
# frozen_string_literal: true

class CustomPizza < Pizza
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  monetize :price_cents

  has_many :orders, dependent: :destroy

  validates :name, presence: true
end

app/models/filling.rb
class Filling < ApplicationRecord
  monetize :price_cents

  has_many :pizza_fillings, dependent: :destroy
  has_many :pizzas, through: :pizza_fillings
end

app/models/order.rb
class Order < ApplicationRecord
  CHECKOUT_STATUSES = { delivery: 0, address: 1, payment: 2, confirm: 3 }.freeze
  FINISHED_STATUSES = { complete: 4, in_progress: 5, in_delivery: 6, delivered: 7, canceled: 8 }.freeze

  monetize :subtotal_cents

  has_many :order_items, dependent: :destroy
  has_many :pizzas, through: :order_items

  has_one :shipping_address, dependent: :destroy
  has_one :card, dependent: :destroy

  belongs_to :user, optional: true
  belongs_to :delivery, optional: true

  accepts_nested_attributes_for :order_items, allow_destroy: true

  enum :status, { **CHECKOUT_STATUSES, **FINISHED_STATUSES }, default: :delivery
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  monetize :price_cents

  belongs_to :pizza
  belongs_to :order

  def additional_fillings
    pizza.fillings.where(type: 'AdditionalFilling')
  end
end

app/models/ordinary_pizza.rb
# frozen_string_literal: true

class OrdinaryPizza < Pizza
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :picturable, polymorphic: true

  validates :image_data, presence: true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  monetize :price_cents

  belongs_to :category
  belongs_to :pizza_dimension

  has_many :reviews, dependent: :destroy
  has_many :pizza_pictures, as: :picturable, dependent: :destroy

  has_many :pizza_fillings, dependent: :destroy
  has_many :fillings, through: :pizza_fillings

  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  accepts_nested_attributes_for :pizza_pictures, allow_destroy: true

  validates :name, presence: true
end

app/models/pizza_filling.rb
class PizzaFilling < ApplicationRecord
  belongs_to :pizza
  belongs_to :filling
end

app/models/pizza_picture.rb
class PizzaPicture < Picture
  include PizzaImageUploader::Attachment(:image)
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :pizza
  belongs_to :user

  enum :status, { unprocessed: 0, approved: 1, rejected: 2 }, default: :unprocessed
end

app/models/shipping.rb
class Shipping < Address
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: %i[github facebook google_oauth2]

  has_one :billing, dependent: :destroy
  has_one :shipping, dependent: :destroy

  has_one :user_picture, as: :picturable, dependent: :destroy

  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy

  accepts_nested_attributes_for :user_picture, allow_destroy: true

  def self.from_omniauth(access_token)
    email = access_token.info['email'].downcase
    user = User.find_by(email:)

    user ||= User.new(
      email:,
      password: Devise.friendly_token[0, 20]
    )
    user.skip_confirmation!
    user.save
    user
  end
end

app/models/user_picture.rb
class UserPicture < Picture
  include UserImageUploader::Attachment(:image)
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items.includes(pizza: %i[pizza_pictures pizza_dimension
                                                                fillings]).decorate.sort_by(&:id)
    @order = current_order.decorate
  end
end

app/helpers/pizza_helper.rb
module PizzaHelper
  def description_length(pizza)
    pizza.description.size > 250
  end

  def description_short(pizza)
    pizza.description.first(250)
  end

  def description_full(pizza)
    pizza.description
  end
end

app/views/carts/_order_items.haml
- @order_items.each do |order_item|
  %tr.table-hover-custom{ class: "#{order_item.id}" }
    %td
      .general-img-wrap-table
        = image_tag(order_item.first_image(:small))
    %td
      %p.title= order_item.pizza.name
      = link_to 'change fillings', edit_custom_pizza_path(order_item_id: order_item.id), class: 'btn btn-primary'
    %td
      %span.font-16.in-gold-500= order_item.pizza.format_price
    %td
      .input-group.output_button
        %a.input-link.d-none.minus-pizza-quantity{ data: { id: order_item.id, pizza_id: order_item.pizza.id, authenticity_token: form_authenticity_token } }
          %i.fa.fa-minus.line-heaght-40
        %input.form-control.quantity-input.quantity{type: "text", value: order_item.quantity, class: "#{order_item.id}",  data: { id: order_item.id, pizza_id: order_item.pizza.id, authenticity_token: form_authenticity_token, total: order_item.price.cents } }
        %a.input-link.d-none.plus-pizza-quantity{ data: { id: order_item.id, pizza_id: order_item.pizza.id, authenticity_token: form_authenticity_token } }
          %i.fa.fa-plus.line-heaght-40
    %td
      %span.font-16.in-gold-500.subtotal{ data: { price: order_item.pizza.price.cents, currency: order_item.price.currency.symbol }, class: "#{order_item.id}" }= order_item.amount_pay.format
    %td
      %button.close.general-cart-close.delete-order-item{type: "button", 'aria-label': "Close", class: "#{order_item.id}", data: { id: order_item.id, authenticity_token: form_authenticity_token } }
        %span{'aria-hidden': "true"} &times;

app/views/carts/show.haml
%main.container.general-main-wrap.fillings.cart-conteiner
  %h1.general-title-margin Cart
  .hidden-xs
    %table.table
      %tr.no-hover
        %th.col-pic.pl-0
          %span.in-grey-600 Product
        %th.col-title
        %th.col-price
          %span.in-grey-600 Price
        %th.col-quantity
          %span.in-grey-600 Quantity
        %th.col-total
          %span.in-grey-600 SubTotal
        %th.col-close
      = render 'carts/order_items'
  .general-order-wrap
    .row
      .move-right
        .res-mr-200.text-center.general-text-right
          %table.general-summary-table.general-summary-table-right.general-text-right
            %tr
              %td
                %strong.font-18.in-gold-500.font-18 Order Total:
              %td
                %strong.font-18.in-gold-500.font-18#total_price= @order.amount_pay.zero? ? @order.amount_pay : @order.amount_pay.format
  .text-center
    = link_to t('.checkout'), fast_authentificate_path, class: "btn btn-default mb-20 hidden-xs center #{'disabled' unless @order_items.any?}"