config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }

  root 'homes#index', as: 'home'

  resources :pizzas, only: %i[show index] do
    resources :reviews, only: :create
  end

  resource :cart, only: %i[show update]
  resource :order_items
  resource :fillings
  resource :custom_pizza

  resource :address, only: %i[edit update]
  resource :user_photo, except: :show
  resource :fast_authentificate, only: %i[create show]

  namespace :checkouts do
    resource :delivery, only: %i[show update]
    resource :address, only: %i[show update]
    resource :payment, only: %i[show create update]
    resource :confirm, only: %i[show create]
    resource :complete, only: %i[show]
  end

  resources :orders, only: %i[show index]
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/billing.rb
class Billing < Address
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :order
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pizzas, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
end

app/models/custom_pizza.rb
# frozen_string_literal: true

class CustomPizza < Pizza
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  monetize :price_cents

  has_many :orders, dependent: :destroy

  validates :name, presence: true
end

app/models/filling.rb
class Filling < ApplicationRecord
  monetize :price_cents

  has_many :pizza_fillings, dependent: :destroy
  has_many :pizzas, through: :pizza_fillings
end

app/models/order.rb
class Order < ApplicationRecord
  CHECKOUT_STATUSES = { delivery: 0, address: 1, payment: 2, confirm: 3 }.freeze
  FINISHED_STATUSES = { complete: 4, in_progress: 5, in_delivery: 6, delivered: 7, canceled: 8 }.freeze

  monetize :subtotal_cents

  has_many :order_items, dependent: :destroy
  has_many :pizzas, through: :order_items

  has_one :shipping_address, dependent: :destroy
  has_one :card, dependent: :destroy

  belongs_to :user, optional: true
  belongs_to :delivery, optional: true

  accepts_nested_attributes_for :order_items, allow_destroy: true

  enum :status, { **CHECKOUT_STATUSES, **FINISHED_STATUSES }, default: :delivery
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  monetize :price_cents

  belongs_to :pizza
  belongs_to :order

  def additional_fillings
    pizza.fillings.where(type: 'AdditionalFilling')
  end
end

app/models/ordinary_pizza.rb
# frozen_string_literal: true

class OrdinaryPizza < Pizza
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :picturable, polymorphic: true

  validates :image_data, presence: true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  monetize :price_cents

  belongs_to :category
  belongs_to :pizza_dimension

  has_many :reviews, dependent: :destroy
  has_many :pizza_pictures, as: :picturable, dependent: :destroy

  has_many :pizza_fillings, dependent: :destroy
  has_many :fillings, through: :pizza_fillings

  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  accepts_nested_attributes_for :pizza_pictures, allow_destroy: true

  validates :name, presence: true
end

app/models/pizza_dimension.rb
class PizzaDimension < ApplicationRecord
  monetize :price_cents

  has_many :pizzas, dependent: :destroy

  validates :dimension, presence: true
end

app/models/pizza_filling.rb
class PizzaFilling < ApplicationRecord
  belongs_to :pizza
  belongs_to :filling
end

app/models/pizza_picture.rb
class PizzaPicture < Picture
  include PizzaImageUploader::Attachment(:image)
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :pizza
  belongs_to :user

  enum :status, { unprocessed: 0, approved: 1, rejected: 2 }, default: :unprocessed
end

app/models/shipping.rb
class Shipping < Address
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: %i[github facebook google_oauth2]

  has_one :billing, dependent: :destroy
  has_one :shipping, dependent: :destroy

  has_one :user_picture, as: :picturable, dependent: :destroy

  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy

  accepts_nested_attributes_for :user_picture, allow_destroy: true

  def self.from_omniauth(access_token)
    email = access_token.info['email'].downcase
    user = User.find_by(email:)

    user ||= User.new(
      email:,
      password: Devise.friendly_token[0, 20]
    )
    user.skip_confirmation!
    user.save
    user
  end
end

app/models/user_picture.rb
class UserPicture < Picture
  include UserImageUploader::Attachment(:image)
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :permit_params, only: :index

  def index
    @pagy, @pizzas = pagy(::Pizzas::PizzasQuery.new(params).call)
    @pizzas = @pizzas.includes([:pizza_pictures]).decorate

    respond_to do |format|
      format.html
      format.json { render json: { html: render_to_string(@pizzas) } }
    end
  end

  def show
    @pizza = Pizza.find(params[:id]).decorate
    @dimensions = PizzaDimension.all
    @review_form = @pizza.reviews.build if user_signed_in?
    @reviews = Review.where(pizza_id: @pizza.id, status: :approved).includes([:user]).decorate
  end

  private

  def permit_params
    @permit_params ||= params.permit(:category_id, :sort_by)
  end
end

app/helpers/fillings_helper.rb
# frozen_string_literal: true

module FillingsHelper
  def include_filling(pizza, filling)
    pizza.fillings.include?(filling)
  end
end

app/helpers/pizza_helper.rb
module PizzaHelper
  def description_length(pizza)
    pizza.description.size > 250
  end

  def description_short(pizza)
    pizza.description.first(250)
  end

  def description_full(pizza)
    pizza.description
  end
end

app/views/pizzas/partials_show/_add_to_cart.haml
= simple_form_for(OrderItem.new,  url: order_items_path(order_id: current_order.id), method: :post) do |f|
  = f.hidden_field :pizza_id, value: @pizza.id
  .col-xs-12.col-md-4
    %p.h1.in-gold-500.mt-10= @pizza.price.format
  .col-xs-7.col-md-5
    = f.submit 'Add to Cart', class: 'btn btn-default pull-right general-position'

app/views/pizzas/partials_show/_review_form.haml
%h3= t('.write_review')
= simple_form_for(@review_form, url: pizza_reviews_path(@pizza), method: :post, wrapper: :profile) do |f|
  %p.general-info-text= t('.scope')
  .mb-15#my_rating
    - (Reviews::ReviewForm::ONE_STAR..Reviews::ReviewForm::MAX_STARS).each do |index|
      %i.fa.fa-star.rate-empty{ value: index , id: "star_#{index}", onclick: "getStars(#{index});" }
  .row  
    .col-md-8
      .mb-40
        = f.hidden_field :pizza_id, value: @pizza.id
        = f.hidden_field :rating
        = f.input :title
        = f.input :review_text
        .text-right
          = f.button :submit, t('.post'), class: 'btn btn-default mb-20', disabled: false

app/views/pizzas/partials_show/_reviews.haml
%h3.in-gold-500.mb-25#reviews{ data: { reviews: @reviews.count } }=  t('.reviews_count', count: @reviews.count)
- @reviews.each do |review|
  .general-message-wrap.divider-lg
    .clearfix
      %span.img-circle.logo-size.logo-empty.media-object= review.user.user_picture ? image_tag(review.user.user_picture.image_url(:tiny)) : review.user_avatar
      .ml-70
        %div
          .general-message-date.hidden-xs= review.review_create_at
          .max-240
            .general-message-verified.pull-right= t('.vefifaed_reviewer')
            .general-message-name= review.user_name
        .mb-15
          - review.rating.times do 
            %i.fa.fa-star.rate-star
          - (Reviews::ReviewForm::MAX_STARS - review.rating).times do 
            %i.fa.fa-star.rate-empty
        %p= review.review_text