config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }

  root 'homes#index', as: 'home'

  resources :pizzas, only: %i[show index] do
    resources :reviews, only: :create
  end

  resource :cart, only: %i[show update]
  resource :order_items
  resource :fillings
  resource :custom_pizza

  resource :address, only: %i[edit update]
  resource :user_photo, except: :show
  resource :fast_authentificate, only: %i[create show]

  namespace :checkouts do
    resource :delivery, only: %i[show update]
    resource :address, only: %i[show update]
    resource :payment, only: %i[show create update]
    resource :confirm, only: %i[show create]
    resource :complete, only: %i[show]
  end

  resources :orders, only: %i[show index]
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/billing.rb
class Billing < Address
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :order
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pizzas, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
end

app/models/custom_pizza.rb
# frozen_string_literal: true

class CustomPizza < Pizza
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  monetize :price_cents

  has_many :orders, dependent: :destroy

  validates :name, presence: true
end

app/models/filling.rb
class Filling < ApplicationRecord
  monetize :price_cents

  has_many :pizza_fillings, dependent: :destroy
  has_many :pizzas, through: :pizza_fillings
end

app/models/order.rb
class Order < ApplicationRecord
  CHECKOUT_STATUSES = { delivery: 0, address: 1, payment: 2, confirm: 3 }.freeze
  FINISHED_STATUSES = { complete: 4, in_progress: 5, in_delivery: 6, delivered: 7, canceled: 8 }.freeze

  monetize :subtotal_cents

  has_many :order_items, dependent: :destroy
  has_many :pizzas, through: :order_items

  has_one :shipping_address, dependent: :destroy
  has_one :card, dependent: :destroy

  belongs_to :user, optional: true
  belongs_to :delivery, optional: true

  accepts_nested_attributes_for :order_items, allow_destroy: true

  enum :status, { **CHECKOUT_STATUSES, **FINISHED_STATUSES }, default: :delivery
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  monetize :price_cents

  belongs_to :pizza
  belongs_to :order

  def additional_fillings
    pizza.fillings.where(type: 'AdditionalFilling')
  end
end

app/models/ordinary_pizza.rb
# frozen_string_literal: true

class OrdinaryPizza < Pizza
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :picturable, polymorphic: true

  validates :image_data, presence: true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  monetize :price_cents

  belongs_to :category
  belongs_to :pizza_dimension

  has_many :reviews, dependent: :destroy
  has_many :pizza_pictures, as: :picturable, dependent: :destroy

  has_many :pizza_fillings, dependent: :destroy
  has_many :fillings, through: :pizza_fillings

  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  accepts_nested_attributes_for :pizza_pictures, allow_destroy: true

  validates :name, presence: true
end

app/models/pizza_dimension.rb
class PizzaDimension < ApplicationRecord
  monetize :price_cents

  has_many :pizzas, dependent: :destroy

  validates :dimension, presence: true
end

app/models/pizza_filling.rb
class PizzaFilling < ApplicationRecord
  belongs_to :pizza
  belongs_to :filling
end

app/models/pizza_picture.rb
class PizzaPicture < Picture
  include PizzaImageUploader::Attachment(:image)
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :pizza
  belongs_to :user

  enum :status, { unprocessed: 0, approved: 1, rejected: 2 }, default: :unprocessed
end

app/models/shipping.rb
class Shipping < Address
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable, omniauth_providers: %i[github facebook google_oauth2]

  has_one :billing, dependent: :destroy
  has_one :shipping, dependent: :destroy

  has_one :user_picture, as: :picturable, dependent: :destroy

  has_many :reviews, dependent: :destroy
  has_many :orders, dependent: :destroy

  accepts_nested_attributes_for :user_picture, allow_destroy: true

  def self.from_omniauth(access_token)
    email = access_token.info['email'].downcase
    user = User.find_by(email:)

    user ||= User.new(
      email:,
      password: Devise.friendly_token[0, 20]
    )
    user.skip_confirmation!
    user.save
    user
  end
end

app/models/user_picture.rb
class UserPicture < Picture
  include UserImageUploader::Attachment(:image)
end

app/controllers/custom_pizzas_controller.rb
class CustomPizzasController < ApplicationController
  before_action :setup_variables, only: %i[new edit]

  def new
    @fillings = OrdinaryFilling.all
  end

  def create
    Pizzas::CreateCustomPizza.call(params:, current_order:)

    redirect_to cart_path
  end

  def edit
    @order_item = OrderItem.find(params[:order_item_id]).decorate
    @fillings = fillings
  end

  def update
    Pizzas::UpdateCustomPizza.call(params:)
  end

  private

  def setup_variables
    @additional_fillings = AdditionalFilling.all
    @pizza_dimensions = PizzaDimension.all
    @dimension_with_price = PizzaDimensions::DimensionsQuery.new(params:).call
  end

  def fillings
    @order_item.pizza.type.to_sym == :CustomPizza ? OrdinaryFilling.all : similar_pizza_fillings
  end

  def similar_pizza_fillings
    Pizza.find_by(name: @order_item.pizza.name).fillings
  end
end

app/helpers/custom_pizzas_helper.rb
module CustomPizzasHelper
  def current_dimension(order_item, dimension)
    return 'selected' if order_item.pizza.pizza_dimension == dimension
  end
end

app/helpers/pizza_helper.rb
module PizzaHelper
  def description_length(pizza)
    pizza.description.size > 250
  end

  def description_short(pizza)
    pizza.description.first(250)
  end

  def description_full(pizza)
    pizza.description
  end
end

app/views/custom_pizzas/edit.haml
.fillings-page
  .filling-menu.dark-theme.dark-block
    .footer-bar
      .button
        .back-to-cart
          = link_to 'Back to cart', cart_path, class: 'btn btn-primary'
    .pizza-menu
      .thumbnail.dark-theme.pizza-image
        .image
          %img{src: "https://i.postimg.cc/63Gn2tYs/9.png"}
        .buttons-set
          %h4 Pizza Dimension
          %select.dark-theme.dark-block#custom_pizza_dimension_edit{ data: { dimensions: @dimension_with_price, order_item_id: @order_item.id, authenticity_token: form_authenticity_token } ,  }
            - @pizza_dimensions.each do |dimension|
              %option{ selected: current_dimension(@order_item, dimension) }= dimension.dimension
        .subtotal-price
          %tr
            %td
              %strong.font-18 Total Price:
            %td
              %strong.font-18#total_price{ data: { price: @order_item.price.cents, currency:  @order_item.amount_pay.currency.symbol  } }= @order_item.amount_pay.format
      .choose-fillings.dark-theme
        .fillings-block
          .border-block
            .fillings-title
              .ordinary-title#ordinary-button.active
                %h1 Fillings
              .additional-title#adding-button
                %h1 Additional Fillings
            .ordinary-fillings#ordinary
              - @fillings.each do |filling|
                .addition-filling
                  .addition-checkbox
                    %input{ type: 'checkbox', checked: include_filling(@order_item.pizza, filling), class: 'complete', name: 'filling', id: 'filling', data: { filling_id: filling.id, price: filling.price.cents,
                     order_item_id: @order_item.id, authenticity_token: form_authenticity_token } }
                  .filling-name
                    %h4= filling.name
                  .price-additianal-filling
                    %h4= filling.price.format
            .additional-fillings#adding.hidden
              - @additional_fillings.each do |filling|
                .addition-filling
                  .addition-checkbox
                    %input{ type: 'checkbox', checked: include_filling(@order_item.pizza, filling), class: 'complete', name: 'filling', id: 'filling', data: { filling_id: filling.id, price: filling.price.cents,
                     order_item_id: @order_item.id, authenticity_token: form_authenticity_token } }
                  .filling-name
                    %h4= filling.name
                  .price-additianal-filling
                    %h4= filling.price.format

app/views/custom_pizzas/new.haml
.fillings-page
  .filling-menu.dark-theme.dark-block
    .footer-bar
      .button
        .back-to-cart
          = link_to 'Back to Menu', pizzas_path, class: 'btn btn-primary'
    = simple_form_for CustomPizza.new, url: custom_pizza_path, method: :post do |f|
      = f.hidden_field :fillings, value: 0, id: 'filling_ids'
      .pizza-menu
        .thumbnail.dark-theme.pizza-image
          .image
            %img{src: "https://i.postimg.cc/63Gn2tYs/9.png"}
          .buttons-set
            %h4 Pizza Dimension
            = f.select(:pizza_dimension, options_for_select(@pizza_dimensions.map{|dimension| dimension.dimension }), {},{ class: 'dark-theme dark-block', data: @dimension_with_price })
          .subtotal-price#total-price
            %tr
              %td
                %strong.font-18 Total Price:
              %td
                %strong.front-18#sub-total{data: { price: 1000, currency: Money.from_cents(0, "USD").currency.symbol} }= Money.from_cents(1000, "USD").format
        .choose-fillings.dark-theme
          .fillings-block
            .border-block
              .fillings-title
                .ordinary-title#ordinary-button.active
                  %h1 Fillings
                .additional-title#adding-button
                  %h1 Additional Fillings
              .ordinary-fillings#ordinary
                - @fillings.each do |filling|
                  .addition-filling
                    .addition-checkbox
                      %input{ type: 'checkbox', name: 'filling', class: 'custom_pizza', data: { filling_id: filling.id, price: filling.price_cents } }
                    .filling-name
                      %h4= filling.name
                    .price-additional-filling
                      %h4= filling.price.format
              .additional-fillings#adding.hidden
                - @additional_fillings.each do |filling|
                  .addition-filling
                    .addition-checkbox
                      %input{ type: 'checkbox', name: 'filling', class: 'custom_pizza', data: { filling_id: filling.id, price: filling.price_cents } }
                    .filling-name
                      %h4= filling.name
                    .price-additional-filling
                      %h4= filling.price.format
        = f.button :submit, 'create pizza', class: 'btn btn-primary custom-pizza-create-button'